version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app: frontend
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - PUBLIC_BACKEND_HOST=backend-${HOST}
      - PUBLIC_BACKEND_PORT=443
      - PUBLIC_TURN_HOST=turn-${HOST}
      - ORIGIN=https://${HOST}
    depends_on:
      - backend
      - turn
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app: backend
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
  turn:
    image: ghcr.io/processone/eturnal:latest
    network_mode: host
    hostname: eturnal
    container_name: eturnal
    restart: unless-stopped
    environment:
      ETURNAL_SECRET: ${AUTH_TOKEN}
  nginx:
    image: nginx:1.23.3-alpine
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - SERVER_NAME=${HOST}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.conf:ro
      - type: tmpfs
        target: /var/lib/coturn
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
